version: "3"
services:
  nodeapp:
    container_name: node-demo
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:4445"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOST: mongodb:27017
    networks:
      - node-app-network
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=app_user
      - MONGO_INITDB_ROOT_PASSWORD=app_password
      - MONGO_INITDB_DATABASE=test
    networks:
      - node-app-network
networks:
  node-app-network:
    driver: bridge